server:
  port: 8901

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5
    enabled: false
endpoints:
  shutdown:
    enabled: true

spring:
  application:
    name: together-user
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:9001}/admin/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

together:
  database:
    url: ${TOGETHER_DATABASE_URL:http://localhost:8902}

info:
  tags:
    environment: local

---
spring:
  profiles: prod

server:
  port: 8080

info:
  tags:
    environment: prod
