server:
  port: 0

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: together-database
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://docker_mysql:3306/together?useSSL=false
    username: root
    password: administrator
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: none
  boot:
    admin:
      client:
        url: http://localhost:8761/admin

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

