server:
  port: 8902

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5
endpoints:
  shutdown:
    enabled: true

spring:
  application:
    name: together-database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_SERVICE_URL:jdbc:mysql://localhost:3306}/together?useSSL=false
    username: root
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: false
        show_sql: false
        format_sql: true
    hibernate:
      ddl-auto: none
  data:
    mongodb:
      uri: ${MONGODB_SERVICE_URL:mongodb://localhost:27017}/together
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:9001}/admin/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

info:
  tags:
    environment: local

---
spring:
  profiles: prod

server:
  port: 8080

info:
  tags:
    environment: prod

