apiVersion: v1
kind: Pod
metadata:
  name: together-status
  labels:
    app: together-status
    component: together-status
spec:
  containers:
    - image: together-status
      imagePullPolicy: Never
      name: together-status
      ports:
        - containerPort: 9001
      env:
        - name: EUREKA_SERVICE_URL
          value: "http://together-discovery:8761" #"eureka" host is resolved by K8s DNS matching the service name
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: together-status
spec:
  ports:
    - port: 9001
  selector:
    app: together-status
    component: together-status
  type: LoadBalancer
