server:
  port: 0

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: together-login
  boot:
    admin:
      client:
        url: http://localhost:8761/admin

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
