apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.root_password }} # 'password' is encoded to base64 using `echo -n 'password' | basre64`
  # to decode the encoded value use echo -n 'cGFzc3dvcmQ=' | base64 --decode
