server:
  port: ${PORT:8761}

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10


spring:
  applicarion:
    name: together-status
  boot:
    admin:
      context-path: /admin

management:
  security:
    enabled: false
