spring:
  boot:
    admin:
      context-path: /admin
  applicarion:
    name: together-status

server:
  port: ${PORT:8761}

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    leaseRenewalIntervalInSeconds: 10

management:
  security:
    enabled: false
