server:
  port: 8080

spring:
  application:
    name: together-status
  boot:
    admin:
      context-path: /
      ui:
        title: "together"
        brand: "together"
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:8080}/admin/

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5
    enabled: false
endpoints:
  shutdown:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false

info:
  tags:
    environment: local

---
spring:
  profiles: prod

server:
  port: 8080

eureka:
  client:
    enabled: true

info:
  tags:
    environment: prod
