server:
  port: 0

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: together-ftp
  boot:
    admin:
      client:
        url: http://localhost:8761/admin

  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      file-size-threshold: 2KB # Threshold after which files are written to disk.
      max-file-size: 200MB # Max file size.
      max-request-size: 215MB # Max Request Size

# All files uploaded through the REST API will be stored in this directory
file:
  upload-dir: ${sys:user.home}/.together/${app.name}/upload

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

info:
  tags:
    environment: test
