spring:
  application:
    name: together-conversation
  profiles:
    active:
      - native
  cloud:
    config:
      uri: http://127.0.0.1:8762
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

server:
  port: 8884

ribbon:
  eureca:
    enabled: false