server:
  port: 8900

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5
endpoints:
  shutdown:
    enabled: true

spring:
  application:
    name: together-gateway
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:9001}/admin/


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  prefix: /api/v1
  stripPrefix: false
  routes:
    together-user-by-service:
      path: /users/**
      serviceId: together-user
      stripPrefix: false
    together-conversation-by-service:
      path: /conversations/**
      serviceId: together-conversation
      stripPrefix: false
