server:
  port: 8887

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: together-gateway
  boot:
    admin:
      client:
        url: http://localhost:8761/admin

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  prefix: /api/v1
  stripPrefix: false
  routes:
#    test:
#      path: /redirect/**
#      url: http://google.com
#    customer-by-address:
#      path: /customer-by-address/**
#      url: http://localhost:9098
    together-user-by-service:
      path: /users/**
      serviceId: together-user
      stripPrefix: false
#    static:
#      path: /static/**
