server:
  port: 8900

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    healthcheck:
      enabled: true
      lease:
        duration: 5
    enabled: false
endpoints:
  shutdown:
    enabled: true

spring:
  application:
    name: together-gateway
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL:http://localhost:9001}/admin/
  sleuth:
    sampler:
      probability: 100
  zipkin:
    baseUrl: ${ZIPKIN_SERVICE_URL:http://localhost:9411}


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

info:
  tags:
    environment: local

zuul:
  prefix: /api/v1
  stripPrefix: false
  routes:
    together-alive-service:
      path: /alive/**
      serviceId: together-alive
      stripPrefix: true
    together-auth-center-service:
      path: /auth/**
      serviceId: together-auth-center
      stripPrefix: true
    together-conversation-service:
      path: /conversations/**
      serviceId: together-conversations
      stripPrefix: true
    together-ftp-service:
      path: /ftp/**
      serviceId: together-ftp
      stripPrefix: true
    together-user-service:
      path: /users/**
      serviceId: together-user
      stripPrefix: true

---
spring:
  profiles: prod

server:
  port: 8080

eureka:
  client:
    enabled: true

info:
  tags:
    environment: prod
