server:
  port: 8888

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: together-config
  boot:
    admin:
      client:
        url: http://localhost:8761/admin

  profiles:
    include: native,default
  cloud:
    config:
      discovery:
        enabled: false
      server:
        native:
          searchLocations: ${sys:user.home}/.together/together-config/config
        encrypt:
          enabled: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

info:
  tags:
    environment: test
