spring:
  application:
    name: together-discovery

server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8080
