name: together CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - created
      - published

jobs:

  root:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clonning codebase
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build together
        run: mvn -B package

  together-discovery:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone codebase
        uses: actions/checkout@v2

      - name: Get the version
        working-directory: ./together-discovery
        id: vars
        run: |
          echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo ::set-output name=tag::$(echo $(git log --oneline|head -n 1|awk '{print $1}'))

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build together-discovery
        working-directory: ./together-discovery
        run: mvn -B package --file pom.xml

      - name: Publish maven package to GitHub
        working-directory: ./together-discovery
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./together-discovery
          file: ./together-discovery/Dockerfile
          tags: docker.pkg.github.com/avijitmondal/together/together-discovery:${{steps.vars.outputs.version}}+${{steps.vars.outputs.tag}}
          github-token: ${{ github.token }}
          push: true

      - name: Published image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  together-status:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone codebase
        uses: actions/checkout@v2

      - name: Get the version
        working-directory: ./together-status
        id: vars
        run: |
          echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
          echo ::set-output name=tag::$(echo $(git log --oneline|head -n 1|awk '{print $1}'))

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build together-status
        working-directory: ./together-status
        run: mvn -B package --file pom.xml

      - name: Publish maven package to GitHub
        working-directory: ./together-status
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: ./together-status
          file: ./together-status/Dockerfile
          tags: docker.pkg.github.com/avijitmondal/together/together-status:${{steps.vars.outputs.version}}+${{steps.vars.outputs.tag}}
          github-token: ${{ github.token }}
          push: true

      - name: Published image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
